package game

var UpgradeIncrements = map[string]float64{
	"maxHp":        50.0,
	"hpRegen":      1.2,
	"speed":        18.0,
	"turnRate":     0.22,
	"bulletDamage": 1.2,
	"bulletSpeed":  50.0,
	"fireRate":     0.8,
	"boostMax":     20.0,
}

var PlaneClasses = map[string]PlaneClass{
	"biplane_scout": {
		ID:          "biplane_scout",
		Name:        "Sopwith Camel",
		Nickname:    "Scout Biplane",
		Tier:        1,
		MinLevel:    1,
		Description: "Nimble starter biplane with twin synchronized machine guns.",
		Evolutions:  []string{"spitfire_ace", "fokker_triplane", "bf109_interceptor"},
		Stats: PlaneStats{
			MaxHP:                240,
			HPRegen:              2.5,
			Speed:                240,
			TurnRate:             2.8,
			BulletDamage:         5.5,
			BulletSpeed:          650,
			FireRate:             4.5,
			BulletSpread:         0.04,
			BulletCount:          2,
			GunOffset:            12,
			BoostMax:             100,
			BoostDrain:           35,
			BoostRegen:           18,
			BoostSpeedMultiplier: 1.45,
			Radius:               24,
		},
		Special: SpecialConfig{
			Type:        "barrel_roll",
			Name:        "Evasive Roll",
			Cooldown:    5.0,
			Description: "Quick barrel roll making you invulnerable to bullets for 0.6s.",
		},
	},
	"spitfire_ace": {
		ID:          "spitfire_ace",
		Name:        "Supermarine Spitfire",
		Nickname:    "All-Round Fighter",
		Tier:        2,
		MinLevel:    10,
		Description: "Iconic British fighter. High fire rate, superb responsiveness, and afterburner boost.",
		Evolutions:  []string{"mustang_p51", "b17_fortress"},
		Stats: PlaneStats{
			MaxHP:                340,
			HPRegen:              3.5,
			Speed:                280,
			TurnRate:             3.2,
			BulletDamage:         6.5,
			BulletSpeed:          750,
			FireRate:             6.5,
			BulletSpread:         0.05,
			BulletCount:          2,
			GunOffset:            16,
			BoostMax:             120,
			BoostDrain:           30,
			BoostRegen:           22,
			BoostSpeedMultiplier: 1.55,
			Radius:               26,
		},
		Special: SpecialConfig{
			Type:        "afterburner",
			Name:        "Supercharger Burst",
			Cooldown:    4.5,
			Description: "Instant 1.5s turbo speed burst leaving thick smoke behind.",
		},
	},
	"fokker_triplane": {
		ID:          "fokker_triplane",
		Name:        "Fokker Dr.I",
		Nickname:    "Red Baron Triplane",
		Tier:        2,
		MinLevel:    10,
		Description: "Unmatched 3-wing turning agility. Tight turn circle for out-maneuvering any tail.",
		Evolutions:  []string{"stuka_dive", "mustang_p51"},
		Stats: PlaneStats{
			MaxHP:                320,
			HPRegen:              4.0,
			Speed:                250,
			TurnRate:             4.2,
			BulletDamage:         7.0,
			BulletSpeed:          700,
			FireRate:             5.5,
			BulletSpread:         0.04,
			BulletCount:          2,
			GunOffset:            10,
			BoostMax:             110,
			BoostDrain:           32,
			BoostRegen:           20,
			BoostSpeedMultiplier: 1.4,
			Radius:               25,
		},
		Special: SpecialConfig{
			Type:        "snap_turn",
			Name:        "180° Snap Turn",
			Cooldown:    4.0,
			Description: "Instantly pivot 180 degrees to counter trailing opponents.",
		},
	},
	"bf109_interceptor": {
		ID:          "bf109_interceptor",
		Name:        "Messerschmitt Bf 109",
		Nickname:    "Heavy Interceptor",
		Tier:        2,
		MinLevel:    10,
		Description: "German interceptor with high top speed and heavy 20mm center cannon.",
		Evolutions:  []string{"me262_jet", "stuka_dive"},
		Stats: PlaneStats{
			MaxHP:                360,
			HPRegen:              3.2,
			Speed:                300,
			TurnRate:             2.6,
			BulletDamage:         9.5,
			BulletSpeed:          820,
			FireRate:             4.2,
			BulletSpread:         0.02,
			BulletCount:          1,
			HasHeavyCenter:       true,
			GunOffset:            14,
			BoostMax:             130,
			BoostDrain:           35,
			BoostRegen:           20,
			BoostSpeedMultiplier: 1.5,
			Radius:               27,
		},
		Special: SpecialConfig{
			Type:        "cannon_burst",
			Name:        "Flak Cannon Burst",
			Cooldown:    5.0,
			Description: "Fires a high-velocity 37mm explosive round.",
		},
	},
	"b17_fortress": {
		ID:          "b17_fortress",
		Name:        "B-17 Flying Fortress",
		Nickname:    "Heavy Bomber",
		Tier:        3,
		MinLevel:    20,
		Description: "Heavily armored behemoth. Automated rear tail turret and heavy carpet bomb drops.",
		Evolutions:  []string{},
		Stats: PlaneStats{
			MaxHP:                750,
			HPRegen:              6.0,
			Speed:                210,
			TurnRate:             1.9,
			BulletDamage:         7.0,
			BulletSpeed:          680,
			FireRate:             4.8,
			BulletSpread:         0.06,
			BulletCount:          4,
			GunOffset:            22,
			HasRearTurret:        true,
			RearTurretDamage:     5.0,
			RearTurretRange:      350,
			RearTurretFireRate:   3.5,
			BoostMax:             140,
			BoostDrain:           40,
			BoostRegen:           15,
			BoostSpeedMultiplier: 1.3,
			Radius:               36,
		},
		Special: SpecialConfig{
			Type:        "carpet_bomb",
			Name:        "Carpet Bombing",
			Cooldown:    6.0,
			Description: "Drops a cluster of 4 high-explosive aerial bombs that detonate behind you.",
		},
	},
	"stuka_dive": {
		ID:          "stuka_dive",
		Name:        "Junkers Ju 87 Stuka",
		Nickname:    "Dive Bomber",
		Tier:        3,
		MinLevel:    20,
		Description: "Iconic dive bomber with twin 37mm Bordkanone cannons and dual heavy aerial rockets.",
		Evolutions:  []string{},
		Stats: PlaneStats{
			MaxHP:                520,
			HPRegen:              4.5,
			Speed:                270,
			TurnRate:             2.7,
			BulletDamage:         11.0,
			BulletSpeed:          780,
			FireRate:             3.8,
			BulletSpread:         0.03,
			BulletCount:          2,
			GunOffset:            20,
			BoostMax:             140,
			BoostDrain:           30,
			BoostRegen:           22,
			BoostSpeedMultiplier: 1.6,
			Radius:               29,
		},
		Special: SpecialConfig{
			Type:        "heavy_rockets",
			Name:        "Dual Heavy Rockets",
			Cooldown:    4.5,
			Description: "Fires two unguided anti-plane/anti-zeppelin rockets with massive explosion radii.",
		},
	},
	"me262_jet": {
		ID:          "me262_jet",
		Name:        "Messerschmitt Me 262",
		Nickname:    "Jet Fighter Prototype",
		Tier:        3,
		MinLevel:    20,
		Description: "First operational jet fighter. Blistering straight-line velocity with 4x MK 108 cannons.",
		Evolutions:  []string{},
		Stats: PlaneStats{
			MaxHP:                450,
			HPRegen:              3.8,
			Speed:                360,
			TurnRate:             2.5,
			BulletDamage:         8.0,
			BulletSpeed:          950,
			FireRate:             7.0,
			BulletSpread:         0.05,
			BulletCount:          4,
			GunOffset:            12,
			IsJet:                true,
			BoostMax:             160,
			BoostDrain:           45,
			BoostRegen:           25,
			BoostSpeedMultiplier: 1.65,
			Radius:               28,
		},
		Special: SpecialConfig{
			Type:        "turbo_ramjet",
			Name:        "Ramjet Supersonic Dash",
			Cooldown:    5.0,
			Description: "Ignites twin turbojets for extreme velocity and instant invulnerable dash.",
		},
	},
	"mustang_p51": {
		ID:          "mustang_p51",
		Name:        "P-51D Mustang",
		Nickname:    "Dominance Fighter",
		Tier:        3,
		MinLevel:    20,
		Description: "Six .50 caliber machine guns, immense stamina boost, and peak combat versatility.",
		Evolutions:  []string{},
		Stats: PlaneStats{
			MaxHP:                480,
			HPRegen:              4.8,
			Speed:                310,
			TurnRate:             3.1,
			BulletDamage:         7.5,
			BulletSpeed:          880,
			FireRate:             6.2,
			BulletSpread:         0.04,
			BulletCount:          4,
			GunOffset:            18,
			BoostMax:             180,
			BoostDrain:           25,
			BoostRegen:           26,
			BoostSpeedMultiplier: 1.5,
			Radius:               27,
		},
		Special: SpecialConfig{
			Type:        "quad_burst",
			Name:        "Full Throttle Overdrive",
			Cooldown:    5.5,
			Description: "Boosts fire rate by 60% and grants unlimited boost stamina for 3 seconds.",
		},
	},
}
